"""
Phase 4: FastAPI backend.

Wraps Phase 2 (retrieval-augmented Q&A) and Phase 3 (agentic gap
analysis) behind a small HTTP API, so the Streamlit frontend (or
anything else) doesn't need to import our internals directly.

Run:
    uvicorn src.api:app --reload --port 8000

Then visit http://localhost:8000/docs for interactive API docs
(auto-generated by FastAPI).
"""
from __future__ import annotations

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from src.agent import run_gap_analysis
from src.ask import answer_question
from src.schema import GapReport

app = FastAPI(
    title="AI Job-Search Copilot API",
    description="Retrieval-augmented Q&A and agentic gap analysis over a candidate profile and job postings.",
    version="0.1.0",
)


class AskRequest(BaseModel):
    question: str


class AskResponse(BaseModel):
    answer: str
    sources: list[str]


class AnalyzeRequest(BaseModel):
    job_text: str
    company_or_role: str = "this role"


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


@app.post("/ask", response_model=AskResponse)
def ask(req: AskRequest) -> AskResponse:
    if not req.question.strip():
        raise HTTPException(status_code=400, detail="Question cannot be empty.")
    try:
        answer, chunks = answer_question(req.question)
    except RuntimeError as e:
        # e.g. missing GROQ_API_KEY
        raise HTTPException(status_code=500, detail=str(e)) from e
    sources = sorted({c.source for c in chunks})
    return AskResponse(answer=answer, sources=sources)


@app.post("/analyze", response_model=GapReport)
def analyze(req: AnalyzeRequest) -> GapReport:
    if not req.job_text.strip():
        raise HTTPException(status_code=400, detail="Job posting text cannot be empty.")
    try:
        report = run_gap_analysis(req.job_text, company_or_role=req.company_or_role)
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=str(e)) from e
    except ValueError as e:
        # e.g. the LLM returned malformed JSON during extraction/assessment
        raise HTTPException(status_code=502, detail=f"Model output error: {e}") from e
    return report
